### ISSUE TITLE
BUG: Error ZIP

### ISSUE THREAD

**Issue by ChrisDevUS** [Goodnato/docker-project#6]
The error says ZipArchive doesn't exist but it has the zip on [line 12](https://github.com/Goodnato/docker-project-php/blob/master/.docker/php/Dockerfile#L12)

![image](https://user-images.githubusercontent.com/47310960/126399197-4b5417e4-0546-474b-a520-2a7442289972.png)

**Comment by Goodnato** [comment]
Thank you for letting me know.
I will make the correction

**Comment by Goodnato** [comment]
Fix PR https://github.com/Goodnato/docker-project-php/pull/7
